{"componentChunkName":"component---src-templates-blog-post-js","path":"/2009/09/nginx-499-error/","result":{"data":{"site":{"siteMetadata":{"domain":"https://www.docunext.com"}},"markdownRemark":{"html":"<p>I got this error when trying to use NGINX as a proxy, setting the http_host header like this:</p>\n<pre>\n    location / {\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header Host $host;\n        proxy_pass http://192.168.8.2:6081/;\n        proxy_connect_timeout 5;\n    }\n</pre>\n<p>Everything worked fine except when clients would send a request without a host field set.</p>\n<p>This happened with a few clients whose job it was to test the server and make sure it ran properly, like monit. To fix the issue, I create a specific location for the test target:</p>\n<pre>\n    location = /test_target.html {\n        root /var/www/public;\n    }\n</pre>","fields":{"slug":"/2009/09/nginx-499-error/"},"frontmatter":{"title":"NGINX 499 Error","date":"September 10th, 2009","tags":"nginx,proxies"}}},"pageContext":{"slug":"/2009/09/nginx-499-error/"}}}